### ISSUE TITLE
Error Messenger.h 

### ISSUE THREAD

**Issue by ahmadabdulrohim** [thomasfredericks/Messenger#2]
when i try install messenger library with include - add zip library, the library messenger was succesfully installed. but when i try a examples(basic_communication) of messenger library, then i compiling this, and i get an error
(basic_communication.pde:18:23: fatal error: Messenger.h: No such file or directory
compilation terminated.
Error compiling.)

can you help me ? please
thankyou

**Comment by thomasfredericks** [comment]
What version of Arduino are you using?

**Comment by thomasfredericks** [comment]
I cannot reproduce your error.
What is your OS and what is its version?

**Comment by thomasfredericks** [comment]
Oh wait, what? How come your file ends with ".pde"?
You are using an outdated version. Please download the new version. 
**Always download the new version when you have a problem!**
